version: '3.1'
services: 
  ganache:
    image: trufflesuite/ganache-cli
    ports: 
      - 8545:8545
    networks:
      - pawningshop
    volumes:
      - ganache_volume:/app/ganache-data
    command:
      - --mnemonic
      - indoor neither various team olympic kit middle involve magnet topic history liar
      - --db
      - /app/ganache-data
      - --networkId
      - '5777'
  mongo:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --replSet rsmongo --shardsvr --port 27017 --bind_ip_all

  mongo1:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --replSet rsmongo --shardsvr --port 27017 --bind_ip_all

  mongo2:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --replSet rsmongo1 --shardsvr --port 27017 --bind_ip_all

  mongo3:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --replSet rsmongo1 --shardsvr --port 27017 --bind_ip_all
  
  mongocfg:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --configsvr --replSet rsmongo1cfg --port 27017 --bind_ip_all

  mongocfg1:
    image: mongo
    networks:
      - pawningshop
    command: /usr/bin/mongod --configsvr --replSet rsmongo1cfg --port 27017 --bind_ip_all

  mongos:
    image: mongo
    networks:
      - pawningshop
    secrets:
      - db_password
      - db_username
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    command: mongos --configdb rsmongo1cfg/mongocfg:27017,mongocfg1:27017 --port 27017  --bind_ip_all
    ports:
      - 27017:27017

  notify:
    image: notify
    build: ./notify
    ports:
      - 7789:7789
    networks:
      - pawningshop

  api:
    image: api
    networks:
      - pawningshop
    env_file: ./api/prod.env

  client: # client service acts like a front-end host and a reverse proxy as well
    image: client
    build: ./client
    ports:
      - 80:80
      - 443:443
    networks:
      - pawningshop
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf

  event_listener:
    image: event_listener
    build: ./event_listener
    env_file: ./event_listener/prod.env
    networks:
      - pawningshop

volumes:
  ganache_volume:
secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
networks: 
  pawningshop: