#https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/
version: '3.1'
services: 
  ganache:
    image: trufflesuite/ganache-cli
    ports: 
      - 8545:8545
    networks:
      - pawningshopdev
    volumes:
      - ganache_volume:/app/ganache-data
    command:
      - --mnemonic
      - indoor neither various team olympic kit middle involve magnet topic history liar
      - --db
      - /app/ganache-data
      - --networkId
      - '5777'
  
  redis:
    image: redis
    networks:
      - pawningshopdev
    ports:
      - 6969:6379
  
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - pawningshopdev
    environment:
    - RABBITMQ_DEFAULT_USER=khanh
    - RABBITMQ_DEFAULT_PASS=handsome
    ports:
      - 5672:5672
      - 15672:15672
    
  mongo:
    image: mongo
    ports:
      - 27018:27018
    volumes:
      - ./mongodb/file.key:/auth/file.key
    env_file:
      - ./mongodb/.env
    networks:
      - pawningshopdev
    command: /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key --bind_ip_all --port 27018

  mongo1:
    image: mongo
    ports:
      - 27019:27019
    volumes:
      - ./mongodb/file.key:/auth/file.key
    networks:
      - pawningshopdev
    command: /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key --bind_ip_all --port 27019

  mongo2:
    image: mongo
    ports:
      - 27020:27020
    volumes:
      - ./mongodb/file.key:/auth/file.key
    networks:
      - pawningshopdev
    command: /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key --bind_ip_all --port 27020

volumes:
  ganache_volume:
secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
networks: 
  pawningshopdev: