version: '3.1'
services: 
  ganache:
    image: trufflesuite/ganache-cli
    ports: 
      - 8545:8545
    networks:
      - pawningshop
    volumes:
      - ganache_volume:/app/ganache-data
    command:
      - --mnemonic
      - jealous expect hundred young unlock disagree major siren surge acoustic machine catalog
      - --db
      - /app/ganache-data
      - --networkId
      - '5777'
  mongo:
    image: mongo
    secrets:
      - db_password
      - db_username
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - pawningshop
    ports:
      - 27017:27017

  notify:
    image: notify
    networks:
      - pawningshop

  api:
    image: api
    networks:
      - pawningshop

  client: # client service acts like a front-end host and a reverse proxy as well
    image: client
    ports:
      - 80:80
      - 443:443
    networks:
      - pawningshop
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf

  event_listener:
    image: event_listener
    env_file: ./event_listener/prod.env
    networks:
      - pawningshop

volumes:
  ganache_volume:
secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
networks: 
  pawningshop: