version: '3.1'
services: 
  ganache:
    image: trufflesuite/ganache-cli
    ports: 
      - 8545:8545
    networks:
      - pawningshopdev
    volumes:
      - ganache_volume:/app/ganache-data
    command:
      - --mnemonic
      - indoor neither various team olympic kit middle involve magnet topic history liar
      - --db
      - /app/ganache-data
      - --networkId
      - '5777'
  
  redis:
    image: redis
    networks:
      - pawningshopdev
    ports:
      - 6969:6379
    
  mongo:
    image: mongo
    ports:
      - 27018:27018
    secrets:
      - db_password
      - db_username
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - pawningshopdev
    command: /usr/bin/mongod --replSet rsmongo --bind_ip_all --port 27018
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 30s
      start_period: 60s

  mongo1:
    image: mongo
    ports:
      - 27019:27019
    secrets:
      - db_password
      - db_username
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - pawningshopdev
    command: /usr/bin/mongod --replSet rsmongo --bind_ip_all --port 27019
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 30s
      start_period: 60s
  
  mongo-replica-setup:
    image: mongo
    restart: on-failure
    networks:
      - pawningshopdev
    volumes:
      - ./mongodb/mongoSetup.sh:/scripts/mongoSetup.sh
    entrypoint: ["bash", "/scripts/mongoSetup.sh" ]
    secrets:
      - db_password
      - db_username
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
        - mongo
        - mongo1

volumes:
  ganache_volume:
secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
networks: 
  pawningshopdev: